### ISSUE TITLE
Lazy fails to compile

### ISSUE THREAD

**Issue by re-thc** [avaje/avaje-inject#895]
Hi, it's great to hear there's compile time lazy but this breaks for some classes. Below is an example with SecureRandom. Same happens to e.g. `jooq` and some other libraries. It works fine with `11.5` but breaks with `11.6` and above.

`  /t0/app/build/generated/sources/annotationProcessor/java/main/org/example/SecureRandom$Lazy.java:16: error: type Provider does not take parameters
    private final Provider<SecureRandom> onceProvider;
`

The code is just

```java
@Lazy
@Factory
public class RandomFactory {
    @Bean
    public SecureRandom secureRandom() {
        return new SecureRandom();
    }
}
```
